config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
 end
  root "dashboard#index"
  resources :todos do
    member do
      patch "strike", to: "todos#strike"
    end
  end
  resources :messages
  resources :tasks do
    collection do
      get :week_view
    end
    member do
      patch :start
      patch :stop
      patch :complete
      patch :restore
      get :edit_name
    end
  end
  resources :settings
  get "/drawings", to: "drawings#broadcast"

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_sessions, dependent: :destroy

  after_create_commit :broadcast_create_task
  after_create_commit :broadcast_scroll

  scope :completed, -> { where(completed: true) }
  scope :incomplete, -> { where(completed: false) }
  scope :current, -> { where(running: true) }

  private

  def broadcast_create_task
    Turbo::StreamsChannel.broadcast_append_to(
      "tasks_#{self.user.id}",
      target: "tasks_#{self.user.id}",
      partial: "tasks/component/task",
      locals: { task: self }
    )
  end

  def broadcast_scroll
    Turbo::StreamsChannel.broadcast_action_to(
      "tasks_#{self.user.id}",
      action: "scroll_to_bottom",
      target: "tasks_#{self.user.id}"
    )
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :cancel_running_task, only: %i[create start]

  def index
    @all_tasks = current_user.tasks.includes(:task_sessions).order(created_at: :desc)
    @running_tasks = current_user.tasks.includes(:task_sessions).incomplete.order(created_at: :desc)
    @completed_tasks = current_user.tasks.includes(:task_sessions).completed.order(created_at: :desc)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(create_params)
    colour = "000000"
    @task.color = "##{colour}"
    @task.user = current_user
    @task.save!
    @task_session = TaskSession.create(task: @task, started_at: Time.current)
  end

  def update
    @task = Task.find(params[:id])
    time_spent = if params[:task][:hours].present? || params[:task][:minutes].present?
             (params[:task][:hours].to_i * 3600) + (params[:task][:minutes].to_i * 60)
    else
             @task.time_spent
    end
    @task.update(update_params.except(:hours, :minutes).merge(time_spent: time_spent))
  end

  def start
    @task = Task.find(params[:id])
    @task_session = TaskSession.create(task: @task, started_at: Time.current)
    @task.update(running: true, last_started_at: Time.current)
  end

  def stop
    @task = Task.find(params[:id])
    @ts = @task.task_sessions.current.first
    @ts.update(ended_at: Time.current, running: false)
    time_spent = @task.time_spent + @ts.time_spent
    @task.update(running: false, time_spent: time_spent)
  end

  def complete
    @task = Task.find(params[:id])
    @task.update(completed: true)
  end

  def restore
    @task = Task.find(params[:id])
    @all_tasks = current_user.tasks.order(created_at: :desc)
    @task.update(completed: false)
  end

  def destroy
    @task = Task.find(destroy_params[:id])
    @task.destroy
  end

  def week_view
    # Get current week's date range (Monday to Sunday)
    start_date = Date.current.beginning_of_week
    end_date = Date.current.end_of_week

    # Filter tasks by current week and include task sessions
    @all_tasks = current_user.tasks.includes(:task_sessions).where(created_at: start_date..end_date).order(created_at: :desc)
    @running_tasks = current_user.tasks.includes(:task_sessions).incomplete.where(created_at: start_date..end_date).order(created_at: :desc)
    @completed_tasks = current_user.tasks.includes(:task_sessions).completed.where(created_at: start_date..end_date).order(created_at: :desc)
  end

  def edit_name
    @task = Task.find(params[:id])
  end


  private

  def create_params
    params.require(:task).permit(:name)
  end

  def update_params
    params.require(:task).permit(:name, :color, :hours, :minutes)
  end

  def destroy_params
    params.permit(:id)
  end

  def cancel_running_task
    @running_task = Task.current.first
    if @running_task.present?
      @running_task&.update(running: false)
      @running_task&.task_sessions.current.first.update(ended_at: Time.current, running: false) if @running_task&.task_sessions.current.present?
    end
  end
end

app/views/tasks/complete.turbo_stream.erb
<%= turbo_stream.remove dom_id(@task) %>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.append "tasks_#{current_user.id}", partial: "tasks/component/task", locals: { task: @task } %>

<%= turbo_stream.replace "tracker_form" do %>
  <%= render partial: "tasks/component/input_form", locals: { message: Task.new } %>
<% end %>
<% if !@running_task.nil? %>
  <%= turbo_stream.replace(@running_task, partial: "tasks/component/task", locals: { task: @running_task }) %>
<% end %>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@task) %>

app/views/tasks/edit.turbo_stream.erb
<%= turbo_stream.replace dom_id(@task) do %>
  <%= render partial: "tasks/component/task_edit", locals: { task: @task } %>
<% end %>

app/views/tasks/edit_name.turbo_stream.erb
<%= turbo_stream.replace "task_#{@task.id}_user_#{@task.user_id}" do %>
  <div class="flex items-center" id="task_<%= @task.id %>_user_<%= @task.user_id %>">
    <%= form_with(model: @task, local: true, class: "w-full", data: { turbo_stream: true }) do |form| %>
      <div class="flex items-center">
        <%= form.text_field :name, class: "border border-black focus:border-gray-300 rounded px-2 py-1 text-sm bg-transparent cursor-text" %>
      </div>
    <% end %>
  </div>
<% end %> 

app/views/tasks/index.html.erb
<div class="min-h-screen bg-gray-100 py-10">
  <div class="container mx-auto px-4 max-w-5xl">
    <div class="flex justify-between items-center mb-6">
      <h1 class="text-3xl font-bold text-indigo-700">Overall Summary</h1>
      <div class="inline-flex rounded-md shadow-sm">
        <%= link_to "All Time", tasks_path, class: "px-4 py-2 text-sm font-medium text-white bg-indigo-700 rounded-l-lg hover:bg-indigo-800 focus:ring-4 focus:outline-none focus:ring-indigo-300", data: { turbo_stream: true } %>
        <%= link_to "By Week", week_view_tasks_path, class: "px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-r-lg hover:bg-indigo-800 focus:ring-4 focus:outline-none focus:ring-indigo-300", data: { turbo_stream: true } %>
      </div>
    </div>
    
    <div id="stats-container">
      <%= render "tasks/item/stats", tasks: @all_tasks %>
    </div>
    
    <div id="summary-container">
      <%= render "tasks/item/summary", completed_tasks: @completed_tasks, running_tasks: @running_tasks %>
    </div>

    <div id="charts-container">
      <%= render "tasks/item/charts" %>
    </div>
  </div>
</div>

app/views/tasks/restore.turbo_stream.erb
<%= turbo_stream.remove dom_id(@task) %>


<%= turbo_stream.replace "distro_#{current_user.id}" do %>
  <div id="distro_<%= current_user.id %>" class="bg-gray-50 p-4 rounded-lg shadow-sm">
    <h3 class="text-lg font-medium text-gray-800 mb-4">Task Completion Distribution</h3>
    <%= column_chart @all_tasks.group(:completed).count,
        colors: ["#F59E0B"],
        library: {
          scales: { y: { beginAtZero: true } },
          xAxes: [{
            ticks: {
              callback: 'function(value) { return value ? "Completed" : "Incomplete"; }'
            }
          }]
        } %>
  </div>
<% end %>

app/views/tasks/show.turbo_stream.erb
<%= turbo_stream.replace dom_id(@task) do %>
  <%= render partial: "tasks/component/task", locals: { task: @task } %>
<% end %>

app/views/tasks/start.turbo_stream.erb
<% if !@running_task.nil? %>
  <%= turbo_stream.replace dom_id(@running_task) do %>
    <%= render partial: "tasks/component/task", locals: { task: @running_task } %>
  <% end %>
<% end %>

<%= turbo_stream.replace dom_id(@task) do %>
  <%= render partial: "tasks/component/task", locals: { task: @task } %>
<% end %>

app/views/tasks/stop.turbo_stream.erb
<%= turbo_stream.replace(@task, partial: "tasks/component/task", locals: { task: @task }) %>

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@task) do %>
  <%= render partial: "tasks/component/task", locals: { task: @task } %>
<% end %> 

app/views/tasks/week_view.turbo_stream.erb
<%= turbo_stream.replace "stats-container" do %>
  <%= render "tasks/item/stats", tasks: @all_tasks %>
<% end %>

<%= turbo_stream.replace "summary-container" do %>
  <%= render "tasks/item/table", completed_tasks: @completed_tasks, running_tasks: @running_tasks %>
<% end %>

<%= turbo_stream.replace "charts-container" do %>
  <%= render "tasks/item/charts" %>
<% end %>