config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
 end
  root "dashboard#index"
  resources :todos do
    member do
      patch "strike", to: "todos#strike"
    end
  end
  resources :messages
  resources :tasks do
    collection do
      get :week_view
    end
    member do
      patch :start
      patch :stop
      patch :complete
      patch :restore
      get :edit_name
    end
  end
  resources :settings
  get "/drawings", to: "drawings#broadcast"

end

app/models/todo.rb
class Todo < ApplicationRecord

  after_create :broadcast_create_todo
  after_create :broadcast_scroll
  after_update :broadcast_update_todo
  after_destroy :broadcast_destroy_todo
  
  private

  def broadcast_update_todo
    Turbo::StreamsChannel.broadcast_replace_to(
      "todos",
      target: "todo_#{id}",
      partial: "todos/component/todo",
      locals: { todo: self }
    )
  end

  def broadcast_create_todo
    Turbo::StreamsChannel.broadcast_append_to(
      "todos",
      target: "todos",
      partial: "todos/component/todo",
      locals: { todo: self }
    )
  end

  def broadcast_destroy_todo
    Turbo::StreamsChannel.broadcast_remove_to(
      "todos",
      target: "todo_#{id}"
    )
  end

  def broadcast_scroll
    Turbo::StreamsChannel.broadcast_action_to(
      "todos",
      action: "scroll_to_bottom",
      target: "todos"
    )
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all.order(created_at: :desc)
  end

  def create
    @todos = Todo.all.order(created_at: :desc)
    @todo = Todo.create!(create_params)
  end

  def destroy
    @todo = Todo.find(destroy_params[:id])
    @todo.destroy!
  end

  def strike
    @todo = Todo.find(update_params[:id])
    @todo.update!(done: !@todo.done)
  end

  private

  def create_params
    params.require(:todo).permit(:name)
  end

  def update_params
    params.permit(:id)
  end

  def destroy_params
    params.permit(:id)
  end
end

app/views/todos/component/_todo.html.erb
<div id="<%= dom_id(todo) %>" class="<%= todo.done ? 'bg-green-50/60' : 'bg-white/50' %> backdrop-filter backdrop-blur-sm border border-white/40 rounded-lg p-3 mb-2 flex items-center justify-between transition-all duration-200">
  <span class="<%= todo.done ? 'line-through text-gray-500' : 'text-gray-800' %> flex-grow">
    <%= todo.name %>
  </span>
  
  <div class="flex space-x-2">
    <%= button_to strike_todo_path(todo), 
      method: :patch, 
      form: { data: { turbo_stream: true } },
      class: "p-1.5 rounded-full hover:bg-gray-100 transition-colors duration-200" do %>
      <% if todo.done %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-green-600" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
        </svg>
      <% else %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-indigo-600" viewBox="0 0 20 20" fill="currentColor">
          <path d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" />
        </svg>
      <% end %>
    <% end %>

    <%= button_to todo_path(todo), 
                  method: :delete, 
                  form: { data: { turbo_stream: true } },
                  class: "p-1.5 rounded-full hover:bg-gray-100 transition-colors duration-200" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-red-600" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
      </svg>
    <% end %>
  </div>
</div>

app/views/todos/component/_todo_card.html.erb
<%= turbo_stream_from "todos" %>
<%= render layout: "shared/card", locals: { title: "Todo List", style: "background-color: #{widget["color"]};", id: "todo-widget" } do %>
  <div class="flex flex-col h-full">
    
    <div class="flex-1 overflow-auto mb-2">
      <%= render 'todos/component/todo_list'%>
    </div>

    <div class="flex-shrink-0">
      <%= render partial: "todos/component/todo_form", locals: { todo: Todo.new } %>
    </div>
  </div>
<% end %>

app/views/todos/component/_todo_form.html.erb
<%= form_with model: todo, id: "todo_form", class: "", data: { turbo: true } do |form| %>
  <div class="flex items-center">
    <%= form.text_field :name, placeholder: "New Todo", class: "flex-grow px-4 py-2 rounded-l-lg border border-gray-300 focus:border-transparent bg-white" %>
    <%= form.submit "Add", class: "bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-2 px-4 rounded-r-lg transition duration-200" %>
  </div>
<% end %>

app/views/todos/component/_todo_list.html.erb
<div id="todos" class="p-2">
  <% @todos.each do |todo| %>
    <%= render partial: "todos/component/todo", locals: { todo: todo } %>
  <% end %>
</div>